from django.urls import path
from .views import (
    MarketingDepartmentView, 
    CompanyAchievementsView, 
    CompanyChallengesView,
    CompanyServicesView,
    CompanyPostsView,
    CompanyPartnersView,
    PartnersReviewsView,
    CompanyApplicationView,
    ApplicationFormView,
    StaticPagesListView,
    StaticPagesDetailView,
    CompanyTeamView,
    CompanyAdvertisingView,
    CompanyVideoReviewsView,
    FAQView,
    CompanyBrendingView,
    CompanyFeaturesView,
    VideoProductionView,
    CRMServiceView,
    MarketingSupportView,
    ServiceOfferingView,
    CompanyPostsItemsListView,
    CompanyPostsItemsDetailView,
)

urlpatterns = [
    path('marketing-department/', MarketingDepartmentView.as_view(), name='marketing-department'),
    path('company-achievements/', CompanyAchievementsView.as_view(), name='company-achievements'),
    path('company-challenges/', CompanyChallengesView.as_view(), name='company-challenges'),
    path('company-services/', CompanyServicesView.as_view(), name='company-services'),
    path('company-posts/', CompanyPostsView.as_view(), name='company-posts'),
    path('company-partners/', CompanyPartnersView.as_view(), name='company-partners'),
    path('partners-reviews/', PartnersReviewsView.as_view(), name='partners-reviews'),
    path('company-application/', CompanyApplicationView.as_view(), name='company-application'),
    path('application-form/', ApplicationFormView.as_view(), name='application-form'),
    path('static-pages/', StaticPagesListView.as_view(), name='static-pages-list'),
    path('static-pages/<slug:slug>/', StaticPagesDetailView.as_view(), name='static-pages-detail'),
    path('company-team/', CompanyTeamView.as_view(), name='company-team'),
    path('company-advertising/', CompanyAdvertisingView.as_view(), name='company-advertising'),
    path('company-video-reviews/', CompanyVideoReviewsView.as_view(), name='company-video-reviews'),
    path('faq/', FAQView.as_view(), name='faq'),
    path('company-brending/', CompanyBrendingView.as_view(), name='company-brending'),
    path('company-features/', CompanyFeaturesView.as_view(), name='company-features'),
    path('video-production/', VideoProductionView.as_view(), name='video-production'),
    path('crm-service/', CRMServiceView.as_view(), name='crm-service'),
    path('marketing-support/', MarketingSupportView.as_view(), name='marketing-support'),
    path('service-offering/', ServiceOfferingView.as_view(), name='service-offering'),
    path('posts/', CompanyPostsItemsListView.as_view(), name='posts-list'),
    path('posts/<int:id>/', CompanyPostsItemsDetailView.as_view(), name='posts-detail'),
]
