from django.urls import path
from .views import (
    MarketingDepartmentView, 
    CompanyAchievementsView, 
    CompanyChallengesView,
    CompanyServicesView,
    CompanyPostsView,
    CompanyPartnersView,
    PartnersReviewsView,
    ApplicationFormView,
    ApplicationFormFirstView,
    ApplicationFormSecondView,
    ApplicationFormThirdView,
    ApplicationFormFourthView,
    ApplicationFormFifthView,
    ApplicationFormSixthView,
    StaticPagesListView,
    StaticPagesDetailView,
    CompanyTeamView,
    CompanyAdvertisingView,
    CompanyVideoReviewsView,
    FAQView,
    CompanyBrendingView,
    CompanyFeaturesView,
    VideoProductionView,
    CRMServiceView,
    MarketingSupportView,
    ServiceOfferingView,
    CompanyPostsItemsListView,
    CompanyPostsItemsDetailView,
    BusinessTypeListView,
    PromotionTypeListView,
    CompanyApplicationListView,
    CompanyApplicationDetailView,
    SiteStatusTypeListView,
    SiteTypeListView,
    ServiceTypeListView,
    VideoTypeListView,
    TaskTypeListView,
    SocialTypeListView,
    ApplicationFormSeventhView,
)

urlpatterns = [
    path('marketing-department/', MarketingDepartmentView.as_view(), name='marketing-department'),
    path('company-achievements/', CompanyAchievementsView.as_view(), name='company-achievements'),
    path('company-challenges/', CompanyChallengesView.as_view(), name='company-challenges'),
    path('company-services/', CompanyServicesView.as_view(), name='company-services'),
    path('company-posts/', CompanyPostsView.as_view(), name='company-posts'),
    path('company-partners/', CompanyPartnersView.as_view(), name='company-partners'),
    path('partners-reviews/', PartnersReviewsView.as_view(), name='partners-reviews'),
    path('application-form/contacts/', ApplicationFormFirstView.as_view(), name='application-form-contacts'),
    path('application-form/business-type/', ApplicationFormView.as_view(), name='application-form-business'),
    path('application-form/publication/', ApplicationFormSecondView.as_view(), name='application-form-publication'),
    path('application-form/site-status/', ApplicationFormThirdView.as_view(), name='application-form-site'),
    path('application-form/service/', ApplicationFormFourthView.as_view(), name='application-form-service'),
    path('application-form/video/', ApplicationFormFifthView.as_view(), name='application-form-video'),
    path('application-form/task/', ApplicationFormSixthView.as_view(), name='application-form-task'),
    path('application-form/site-type/', ApplicationFormSeventhView.as_view(), name='application-form-site-type'),
    path('static-pages/', StaticPagesListView.as_view(), name='static-pages-list'),
    path('static-pages/<slug:slug>/', StaticPagesDetailView.as_view(), name='static-pages-detail'),
    path('company-team/', CompanyTeamView.as_view(), name='company-team'),
    path('company-advertising/', CompanyAdvertisingView.as_view(), name='company-advertising'),
    path('company-video-reviews/', CompanyVideoReviewsView.as_view(), name='company-video-reviews'),
    path('faq/', FAQView.as_view(), name='faq'),
    path('company-brending/', CompanyBrendingView.as_view(), name='company-brending'),
    path('company-features/', CompanyFeaturesView.as_view(), name='company-features'),
    path('video-production/', VideoProductionView.as_view(), name='video-production'),
    path('crm-service/', CRMServiceView.as_view(), name='crm-service'),
    path('marketing-support/', MarketingSupportView.as_view(), name='marketing-support'),
    path('service-offering/', ServiceOfferingView.as_view(), name='service-offering'),
    path('posts/', CompanyPostsItemsListView.as_view(), name='posts-list'),
    path('posts/<int:id>/', CompanyPostsItemsDetailView.as_view(), name='posts-detail'),
    path('business-types/', BusinessTypeListView.as_view(), name='business-types'),
    path('promotion-types/', PromotionTypeListView.as_view(), name='promotion-types'),
    path('site-status/', SiteStatusTypeListView.as_view(), name='site-types'),
    path('site-types/', SiteTypeListView.as_view(), name='site-types'),
    path('service-types/', ServiceTypeListView.as_view(), name='service_types'),
    path('video-types/', VideoTypeListView.as_view(), name='video_types'),
    path('task-types/', TaskTypeListView.as_view(), name='task_types'),
    path('social-types/', SocialTypeListView.as_view(), name='social_types'),
    path('company-applications/', CompanyApplicationListView.as_view(), name='company-applications-list'),
    path('company-applications/<int:id>/', CompanyApplicationDetailView.as_view(), name='company-application-detail'),
]
