# Generated by Django 5.1.5 on 2025-01-31 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='company/logo/', verbose_name='Логотип')),
                ('description', models.TextField(help_text='Например: Bold Brands International ваш внешний отдел маркетинга', verbose_name='Описание')),
                ('whatsapp_logo', models.FileField(upload_to='company/whatsapp_logo/', verbose_name='Логотип Whatsapp')),
                ('whatsapp_link', models.URLField(help_text='Например: https://wa.me/996555555555', verbose_name='Whatsapp ссылка')),
                ('whatsapp_text', models.CharField(help_text='Например: Напишите нам на Whatsapp', max_length=255, verbose_name='Текст Whatsapp')),
                ('work_time', models.CharField(help_text='Например: Пн-Пт: 09:00-18:00', max_length=255, verbose_name='Время работы')),
                ('video', models.FileField(help_text='Например: https://www.youtube.com/watch?v=dQw4w9WgXcQ', upload_to='company/video/', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Адрес (Бишкек)', max_length=255, verbose_name='Название')),
                ('address', models.CharField(help_text='Например: г. Бишкек, ул. Ахунбаева 123', max_length=255, verbose_name='Адрес')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='site_info.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Email (Бишкек)', max_length=255, verbose_name='Название')),
                ('email', models.EmailField(help_text='Например: info@boldbrands.kg', max_length=255, verbose_name='Email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='site_info.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Телефон (Бишкек)', max_length=255, verbose_name='Название')),
                ('phone', models.CharField(help_text='Например: +996 555 555 555', max_length=255, verbose_name='Телефон')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='site_info.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефоны',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='company/social_networks/', verbose_name='Логотип')),
                ('link', models.URLField(help_text='Например: https://www.instagram.com/boldbrands.kg', verbose_name='Ссылка')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='site_info.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
