# Generated by Django 5.1.5 on 2025-02-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_en',
            field=models.CharField(help_text='Например: г. Бишкек, ул. Ахунбаева 123', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_ru',
            field=models.CharField(help_text='Например: г. Бишкек, ул. Ахунбаева 123', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_uz',
            field=models.CharField(help_text='Например: г. Бишкек, ул. Ахунбаева 123', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='address',
            name='title_en',
            field=models.CharField(help_text='Например: Адрес (Бишкек)', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='address',
            name='title_ru',
            field=models.CharField(help_text='Например: Адрес (Бишкек)', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='address',
            name='title_uz',
            field=models.CharField(help_text='Например: Адрес (Бишкек)', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_en',
            field=models.TextField(help_text='Например: Bold Brands International ваш внешний отдел маркетинга', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_ru',
            field=models.TextField(help_text='Например: Bold Brands International ваш внешний отдел маркетинга', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description_uz',
            field=models.TextField(help_text='Например: Bold Brands International ваш внешний отдел маркетинга', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_text_en',
            field=models.CharField(help_text='Например: Напишите нам на Whatsapp', max_length=255, null=True, verbose_name='Текст Whatsapp'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_text_ru',
            field=models.CharField(help_text='Например: Напишите нам на Whatsapp', max_length=255, null=True, verbose_name='Текст Whatsapp'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='whatsapp_text_uz',
            field=models.CharField(help_text='Например: Напишите нам на Whatsapp', max_length=255, null=True, verbose_name='Текст Whatsapp'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='work_time_en',
            field=models.CharField(help_text='Например: Пн-Пт: 09:00-18:00', max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='work_time_ru',
            field=models.CharField(help_text='Например: Пн-Пт: 09:00-18:00', max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='work_time_uz',
            field=models.CharField(help_text='Например: Пн-Пт: 09:00-18:00', max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AddField(
            model_name='emails',
            name='email_en',
            field=models.EmailField(help_text='Например: info@boldbrands.kg', max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='emails',
            name='email_ru',
            field=models.EmailField(help_text='Например: info@boldbrands.kg', max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='emails',
            name='email_uz',
            field=models.EmailField(help_text='Например: info@boldbrands.kg', max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='emails',
            name='title_en',
            field=models.CharField(help_text='Например: Email (Бишкек)', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='emails',
            name='title_ru',
            field=models.CharField(help_text='Например: Email (Бишкек)', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='emails',
            name='title_uz',
            field=models.CharField(help_text='Например: Email (Бишкек)', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='phones',
            name='phone_en',
            field=models.CharField(help_text='Например: +996 555 555 555', max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='phones',
            name='phone_ru',
            field=models.CharField(help_text='Например: +996 555 555 555', max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='phones',
            name='phone_uz',
            field=models.CharField(help_text='Например: +996 555 555 555', max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='phones',
            name='title_en',
            field=models.CharField(help_text='Например: Телефон (Бишкек)', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='phones',
            name='title_ru',
            field=models.CharField(help_text='Например: Телефон (Бишкек)', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='phones',
            name='title_uz',
            field=models.CharField(help_text='Например: Телефон (Бишкек)', max_length=255, null=True, verbose_name='Название'),
        ),
    ]
