# Generated by Django 5.1.5 on 2025-03-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0002_address_address_en_address_address_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='production_video',
            field=models.FileField(blank=True, help_text='Загрузите видео для главной Видеопродакшн', null=True, upload_to='company/video/', verbose_name='Видео (для страницы Видеопродакшн)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(help_text='Загрузите видео для главной страницы', upload_to='company/video/', verbose_name='Видео'),
        ),
    ]
