# Generated by Django 5.1.5 on 2025-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0003_companyinfo_production_video_alter_companyinfo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='production_video',
            field=models.FileField(blank=True, help_text='Загрузите видео для страницы Видеопродакшн', null=True, upload_to='company/video/', verbose_name='Видео (для страницы Видеопродакшн)'),
        ),
    ]
