# Generated by Django 5.1.5 on 2025-03-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_info', '0004_alter_companyinfo_production_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='production_video',
            field=models.URLField(blank=True, help_text='Вставьте ссылку видео для страницы Видеопродакшн', null=True, verbose_name='Видео (для страницы Видеопродакшн)'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video',
            field=models.URLField(help_text='Вставьте ссылку видео для главной страницы', verbose_name='Видео'),
        ),
    ]
