# Generated by Django 5.1.5 on 2025-01-31 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: BoldBrends International', max_length=255, verbose_name='Название')),
                ('sub_title', models.CharField(help_text='Например: Мы поможем вам найти бренды, которые вам нужны', max_length=255, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Отдел маркетинга',
                'verbose_name_plural': 'Отделы маркетинга',
            },
        ),
        migrations.CreateModel(
            name='MarketingDepartmentChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Например: 01', verbose_name='Номер главы')),
                ('title', models.CharField(help_text='Например: Глава 1', max_length=255, verbose_name='Название главы')),
                ('marketing_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.marketingdepartment', verbose_name='Отдел маркетинга')),
            ],
            options={
                'verbose_name': 'Глава отдела маркетинга',
                'verbose_name_plural': 'Главы отделов маркетинга',
                'ordering': ['-id'],
            },
        ),
    ]
