# Generated by Django 5.1.5 on 2025-01-31 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingdepartmentchapters',
            name='marketing_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='pages.marketingdepartment', verbose_name='Отдел маркетинга'),
        ),
        migrations.AlterField(
            model_name='marketingdepartmentchapters',
            name='number',
            field=models.CharField(help_text='Например: 01', max_length=255, verbose_name='Номер главы'),
        ),
    ]
