# Generated by Django 5.1.5 on 2025-01-31 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_marketingdepartmentchapters_marketing_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: BoldBrends International', max_length=255, verbose_name='Название')),
                ('sub_title', models.CharField(help_text='Например: совместно создаем прочную ...', max_length=255, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Достижение компании',
                'verbose_name_plural': 'Достижения компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyAchievementsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Топ-1', max_length=255, verbose_name='Название')),
                ('sub_title', models.CharField(help_text='Например: маркетинговая компания по версии The Great 2023...', max_length=255, verbose_name='Подзаголовок')),
                ('company_achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.companyachievements', verbose_name='Достижение компании')),
            ],
            options={
                'verbose_name': 'Достижение компании',
                'verbose_name_plural': 'Достижения компании',
                'ordering': ['-id'],
            },
        ),
    ]
