# Generated by Django 5.1.5 on 2025-01-31 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_companyachievements_companyachievementsitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyChallenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Что мешает вашему бизнесу?', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Проблема компании',
                'verbose_name_plural': 'Проблемы компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyChallengesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='company_challenges_logos/', verbose_name='Логотип')),
                ('title', models.CharField(help_text='Например: Отсутствие маркетинговой стратегии', max_length=255, verbose_name='Название')),
                ('description', models.TextField(help_text='Например: Без четкого плана результаты будут хаотичными.', verbose_name='Описание')),
                ('company_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.companychallenges', verbose_name='Проблема компании')),
            ],
            options={
                'verbose_name': 'Проблема компании',
                'verbose_name_plural': 'Проблемы компании',
                'ordering': ['-id'],
            },
        ),
    ]
