# Generated by Django 5.1.5 on 2025-01-31 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_companychallenges_companychallengesitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Выводим компании в ТОП ...', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Услуга компании',
                'verbose_name_plural': 'Услуги компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyServicesItemsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(help_text='Например: Маркетинговая стратегия, SEO, SMM, PR', max_length=255, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Тег услуги компании',
                'verbose_name_plural': 'Теги услуг компании',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyServicesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Маркетинговая стратегия', max_length=255, verbose_name='Название')),
                ('image', models.FileField(upload_to='company_services_images/', verbose_name='Изображение')),
                ('company_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.companyservices', verbose_name='Услуга компании')),
                ('tags', models.ManyToManyField(related_name='items', to='pages.companyservicesitemstags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Услуга компании',
                'verbose_name_plural': 'Услуги компании',
                'ordering': ['-id'],
            },
        ),
    ]
