# Generated by Django 5.1.5 on 2025-01-31 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_companyservices_companyservicesitemstags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyServicesItemsTags',
            new_name='Tags',
        ),
    ]
