# Generated by Django 5.1.5 on 2025-02-01 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_companyservicesitemstags_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Как мы помогли другим...', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Пост компании',
                'verbose_name_plural': 'Посты компании',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Instagram', max_length=255, verbose_name='Название')),
                ('logo', models.FileField(upload_to='social_media_logos/', verbose_name='Логотип')),
                ('subscribers', models.CharField(help_text='Например: +10,5 подписчиков', max_length=255, verbose_name='Подписчики')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tags',
            new_name='name',
        ),
        migrations.CreateModel(
            name='CompanyPostsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='company_posts_images/', verbose_name='Изображение')),
                ('title', models.CharField(help_text='Например: Увеличили выручку корейского ресторана на 70%...', max_length=255, verbose_name='Название')),
                ('company_name', models.CharField(help_text='Например: Корейский ресторан', max_length=255, verbose_name='Название компании')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('company_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.companyposts', verbose_name='Пост компании')),
                ('tags', models.ManyToManyField(related_name='post_items', to='pages.tags', verbose_name='Теги')),
                ('social_media', models.ManyToManyField(related_name='post_items', to='pages.socialmedia', verbose_name='Социальные сети')),
            ],
            options={
                'verbose_name': 'Пост компании',
                'verbose_name_plural': 'Посты компании',
                'ordering': ['-id'],
            },
        ),
    ]
