# Generated by Django 5.1.5 on 2025-02-01 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_companyposts_socialmedia_rename_tags_tags_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Наши партнеры', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Партнер компании',
                'verbose_name_plural': 'Партнеры компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyPartnersItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.FileField(upload_to='company_partners_logos/', verbose_name='Логотип компании')),
                ('company_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.companypartners', verbose_name='Партнер компании')),
            ],
            options={
                'verbose_name': 'Партнер компании',
                'verbose_name_plural': 'Партнеры компании',
                'ordering': ['-id'],
            },
        ),
    ]
