# Generated by Django 5.1.5 on 2025-02-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_companypartners_companypartnersitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypartnersitems',
            name='company_name',
            field=models.CharField(default=1, help_text='Например: Bigser', max_length=255, verbose_name='Название компании'),
            preserve_default=False,
        ),
    ]
