# Generated by Django 5.1.5 on 2025-02-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_companypartnersitems_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Отзывы наших партнеров', max_length=255, verbose_name='Название')),
                ('description', models.TextField(help_text='Например: Мы очень довольны работой с компанией BoldBrends...', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отзыв партнера',
                'verbose_name_plural': 'Отзывы партнеров',
            },
        ),
        migrations.CreateModel(
            name='PartnersReviewsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Рейтинг')),
                ('user_image', models.FileField(upload_to='partners_reviews_images/', verbose_name='Изображение пользователя')),
                ('user_name', models.CharField(help_text='Например: John Doe', max_length=255, verbose_name='Имя пользователя')),
                ('user_position', models.CharField(help_text='Например: CEO', max_length=255, verbose_name='Должность пользователя')),
                ('text', models.TextField(help_text='Например: Мы очень довольны работой с компанией BoldBrends...', verbose_name='Текст отзыва')),
                ('partner_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.partnersreviews', verbose_name='Отзыв партнера')),
            ],
            options={
                'verbose_name': 'Отзыв партнера',
                'verbose_name_plural': 'Отзывы партнеров',
                'ordering': ['-id'],
            },
        ),
    ]
