# Generated by Django 5.1.5 on 2025-02-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_partnersreviews_partnersreviewsitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(help_text='Например: John Doe', max_length=255, verbose_name='Имя отправителя')),
                ('sender_phone', models.CharField(help_text='Например: +7 999 999 99 99', max_length=255, verbose_name='Телефон отправителя')),
                ('sender_email', models.EmailField(help_text='Например: john.doe@example.com', max_length=255, verbose_name='Email отправителя')),
            ],
            options={
                'verbose_name': 'Форма заявки на партнерство',
                'verbose_name_plural': 'Формы заявок на партнерство',
            },
        ),
        migrations.CreateModel(
            name='CompanyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Оставить заявку на партнерство', max_length=255, verbose_name='Название')),
                ('sub_title', models.CharField(help_text='Например: Мы свяжемся с вами в ближайшее время', max_length=255, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Заявка на партнерство',
                'verbose_name_plural': 'Заявки на партнерство',
            },
        ),
    ]
