# Generated by Django 5.1.5 on 2025-02-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_applicationform_companyapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: О компании', max_length=255, verbose_name='Название')),
                ('content', models.TextField(help_text='Например: Мы компания BoldBrends...', verbose_name='Контент')),
                ('image', models.FileField(upload_to='static_pages_images/', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
    ]
