# Generated by Django 5.1.5 on 2025-02-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_staticpages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='name',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='staticpages',
            name='content_en',
            field=models.TextField(help_text='Например: Мы компания BoldBrends...', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='staticpages',
            name='content_ru',
            field=models.TextField(help_text='Например: Мы компания BoldBrends...', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='staticpages',
            name='content_uz',
            field=models.TextField(help_text='Например: Мы компания BoldBrends...', null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='staticpages',
            name='title_en',
            field=models.CharField(help_text='Например: О компании', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='staticpages',
            name='title_ru',
            field=models.CharField(help_text='Например: О компании', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='staticpages',
            name='title_uz',
            field=models.CharField(help_text='Например: О компании', max_length=255, null=True, verbose_name='Название'),
        ),
    ]
