# Generated by Django 5.1.5 on 2025-02-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_rename_name_tags_tags_staticpages_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyachievements',
            name='sub_title_en',
            field=models.CharField(help_text='Например: совместно создаем прочную ...', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='companyachievements',
            name='sub_title_ru',
            field=models.CharField(help_text='Например: совместно создаем прочную ...', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='companyachievements',
            name='sub_title_uz',
            field=models.CharField(help_text='Например: совместно создаем прочную ...', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='companyachievements',
            name='title_en',
            field=models.CharField(help_text='Например: BoldBrends International', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyachievements',
            name='title_ru',
            field=models.CharField(help_text='Например: BoldBrends International', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyachievements',
            name='title_uz',
            field=models.CharField(help_text='Например: BoldBrends International', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyachievementsitems',
            name='sub_title_en',
            field=models.CharField(help_text='Например: маркетинговая компания по версии The Great 2023...', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='companyachievementsitems',
            name='sub_title_ru',
            field=models.CharField(help_text='Например: маркетинговая компания по версии The Great 2023...', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='companyachievementsitems',
            name='sub_title_uz',
            field=models.CharField(help_text='Например: маркетинговая компания по версии The Great 2023...', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='companyachievementsitems',
            name='title_en',
            field=models.CharField(help_text='Например: Топ-1', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyachievementsitems',
            name='title_ru',
            field=models.CharField(help_text='Например: Топ-1', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyachievementsitems',
            name='title_uz',
            field=models.CharField(help_text='Например: Топ-1', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='sub_title_en',
            field=models.CharField(help_text='Например: Мы свяжемся с вами в ближайшее время', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='sub_title_ru',
            field=models.CharField(help_text='Например: Мы свяжемся с вами в ближайшее время', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='sub_title_uz',
            field=models.CharField(help_text='Например: Мы свяжемся с вами в ближайшее время', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='title_en',
            field=models.CharField(help_text='Например: Оставить заявку на партнерство', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='title_ru',
            field=models.CharField(help_text='Например: Оставить заявку на партнерство', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyapplication',
            name='title_uz',
            field=models.CharField(help_text='Например: Оставить заявку на партнерство', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companychallenges',
            name='title_en',
            field=models.CharField(help_text='Например: Что мешает вашему бизнесу?', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companychallenges',
            name='title_ru',
            field=models.CharField(help_text='Например: Что мешает вашему бизнесу?', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companychallenges',
            name='title_uz',
            field=models.CharField(help_text='Например: Что мешает вашему бизнесу?', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companychallengesitems',
            name='description_en',
            field=models.TextField(help_text='Например: Без четкого плана результаты будут хаотичными.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companychallengesitems',
            name='description_ru',
            field=models.TextField(help_text='Например: Без четкого плана результаты будут хаотичными.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companychallengesitems',
            name='description_uz',
            field=models.TextField(help_text='Например: Без четкого плана результаты будут хаотичными.', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='companychallengesitems',
            name='title_en',
            field=models.CharField(help_text='Например: Отсутствие маркетинговой стратегии', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companychallengesitems',
            name='title_ru',
            field=models.CharField(help_text='Например: Отсутствие маркетинговой стратегии', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companychallengesitems',
            name='title_uz',
            field=models.CharField(help_text='Например: Отсутствие маркетинговой стратегии', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companypartners',
            name='title_en',
            field=models.CharField(help_text='Например: Наши партнеры', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companypartners',
            name='title_ru',
            field=models.CharField(help_text='Например: Наши партнеры', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companypartners',
            name='title_uz',
            field=models.CharField(help_text='Например: Наши партнеры', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companypartnersitems',
            name='company_name_en',
            field=models.CharField(help_text='Например: Bigser', max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='companypartnersitems',
            name='company_name_ru',
            field=models.CharField(help_text='Например: Bigser', max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='companypartnersitems',
            name='company_name_uz',
            field=models.CharField(help_text='Например: Bigser', max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='companyposts',
            name='title_en',
            field=models.CharField(help_text='Например: Как мы помогли другим...', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyposts',
            name='title_ru',
            field=models.CharField(help_text='Например: Как мы помогли другим...', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyposts',
            name='title_uz',
            field=models.CharField(help_text='Например: Как мы помогли другим...', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companypostsitems',
            name='company_name_en',
            field=models.CharField(help_text='Например: Корейский ресторан', max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='companypostsitems',
            name='company_name_ru',
            field=models.CharField(help_text='Например: Корейский ресторан', max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='companypostsitems',
            name='company_name_uz',
            field=models.CharField(help_text='Например: Корейский ресторан', max_length=255, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='companypostsitems',
            name='title_en',
            field=models.CharField(help_text='Например: Увеличили выручку корейского ресторана на 70%...', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companypostsitems',
            name='title_ru',
            field=models.CharField(help_text='Например: Увеличили выручку корейского ресторана на 70%...', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companypostsitems',
            name='title_uz',
            field=models.CharField(help_text='Например: Увеличили выручку корейского ресторана на 70%...', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyservices',
            name='title_en',
            field=models.CharField(help_text='Например: Выводим компании в ТОП ...', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyservices',
            name='title_ru',
            field=models.CharField(help_text='Например: Выводим компании в ТОП ...', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyservices',
            name='title_uz',
            field=models.CharField(help_text='Например: Выводим компании в ТОП ...', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyservicesitems',
            name='title_en',
            field=models.CharField(help_text='Например: Маркетинговая стратегия', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyservicesitems',
            name='title_ru',
            field=models.CharField(help_text='Например: Маркетинговая стратегия', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='companyservicesitems',
            name='title_uz',
            field=models.CharField(help_text='Например: Маркетинговая стратегия', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='marketingdepartment',
            name='sub_title_en',
            field=models.CharField(help_text='Например: Мы поможем вам найти бренды, которые вам нужны', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='marketingdepartment',
            name='sub_title_ru',
            field=models.CharField(help_text='Например: Мы поможем вам найти бренды, которые вам нужны', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='marketingdepartment',
            name='sub_title_uz',
            field=models.CharField(help_text='Например: Мы поможем вам найти бренды, которые вам нужны', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='marketingdepartment',
            name='title_en',
            field=models.CharField(help_text='Например: BoldBrends International', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='marketingdepartment',
            name='title_ru',
            field=models.CharField(help_text='Например: BoldBrends International', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='marketingdepartment',
            name='title_uz',
            field=models.CharField(help_text='Например: BoldBrends International', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='marketingdepartmentchapters',
            name='title_en',
            field=models.CharField(help_text='Например: Глава 1', max_length=255, null=True, verbose_name='Название главы'),
        ),
        migrations.AddField(
            model_name='marketingdepartmentchapters',
            name='title_ru',
            field=models.CharField(help_text='Например: Глава 1', max_length=255, null=True, verbose_name='Название главы'),
        ),
        migrations.AddField(
            model_name='marketingdepartmentchapters',
            name='title_uz',
            field=models.CharField(help_text='Например: Глава 1', max_length=255, null=True, verbose_name='Название главы'),
        ),
        migrations.AddField(
            model_name='partnersreviews',
            name='description_en',
            field=models.TextField(help_text='Например: Мы очень довольны работой с компанией BoldBrends...', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partnersreviews',
            name='description_ru',
            field=models.TextField(help_text='Например: Мы очень довольны работой с компанией BoldBrends...', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partnersreviews',
            name='description_uz',
            field=models.TextField(help_text='Например: Мы очень довольны работой с компанией BoldBrends...', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partnersreviews',
            name='title_en',
            field=models.CharField(help_text='Например: Отзывы наших партнеров', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partnersreviews',
            name='title_ru',
            field=models.CharField(help_text='Например: Отзывы наших партнеров', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partnersreviews',
            name='title_uz',
            field=models.CharField(help_text='Например: Отзывы наших партнеров', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partnersreviewsitems',
            name='text_en',
            field=models.TextField(help_text='Например: Мы очень довольны работой с компанией BoldBrends...', null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='partnersreviewsitems',
            name='text_ru',
            field=models.TextField(help_text='Например: Мы очень довольны работой с компанией BoldBrends...', null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='partnersreviewsitems',
            name='text_uz',
            field=models.TextField(help_text='Например: Мы очень довольны работой с компанией BoldBrends...', null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='partnersreviewsitems',
            name='user_name_en',
            field=models.CharField(help_text='Например: John Doe', max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='partnersreviewsitems',
            name='user_name_ru',
            field=models.CharField(help_text='Например: John Doe', max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='partnersreviewsitems',
            name='user_name_uz',
            field=models.CharField(help_text='Например: John Doe', max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='partnersreviewsitems',
            name='user_position_en',
            field=models.CharField(help_text='Например: CEO', max_length=255, null=True, verbose_name='Должность пользователя'),
        ),
        migrations.AddField(
            model_name='partnersreviewsitems',
            name='user_position_ru',
            field=models.CharField(help_text='Например: CEO', max_length=255, null=True, verbose_name='Должность пользователя'),
        ),
        migrations.AddField(
            model_name='partnersreviewsitems',
            name='user_position_uz',
            field=models.CharField(help_text='Например: CEO', max_length=255, null=True, verbose_name='Должность пользователя'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='subscribers_en',
            field=models.CharField(help_text='Например: +10,5 подписчиков', max_length=255, null=True, verbose_name='Подписчики'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='subscribers_ru',
            field=models.CharField(help_text='Например: +10,5 подписчиков', max_length=255, null=True, verbose_name='Подписчики'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='subscribers_uz',
            field=models.CharField(help_text='Например: +10,5 подписчиков', max_length=255, null=True, verbose_name='Подписчики'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='title_en',
            field=models.CharField(help_text='Например: Instagram', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='title_ru',
            field=models.CharField(help_text='Например: Instagram', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='title_uz',
            field=models.CharField(help_text='Например: Instagram', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tags_en',
            field=models.CharField(help_text='Например: Маркетинговая стратегия, SEO, SMM, PR', max_length=255, null=True, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tags_ru',
            field=models.CharField(help_text='Например: Маркетинговая стратегия, SEO, SMM, PR', max_length=255, null=True, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tags_uz',
            field=models.CharField(help_text='Например: Маркетинговая стратегия, SEO, SMM, PR', max_length=255, null=True, verbose_name='Теги'),
        ),
    ]
