# Generated by Django 5.1.5 on 2025-02-02 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_companyteam_companyteamitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAdvertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Контент который продает', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Контент который продает', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Контент который продает', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Контент который продает', max_length=255, null=True, verbose_name='Название')),
                ('sub_title', models.CharField(help_text='Например: Мы создаем визуалы, которые выделяют ваш бренд среди конкурентов', max_length=255, verbose_name='Подзаголовок')),
                ('sub_title_ru', models.CharField(help_text='Например: Мы создаем визуалы, которые выделяют ваш бренд среди конкурентов', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('sub_title_en', models.CharField(help_text='Например: Мы создаем визуалы, которые выделяют ваш бренд среди конкурентов', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('sub_title_uz', models.CharField(help_text='Например: Мы создаем визуалы, которые выделяют ваш бренд среди конкурентов', max_length=255, null=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Реклама компании',
                'verbose_name_plural': 'Реклама компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyAdvertisingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='company_advertising_images/', verbose_name='Изображение')),
                ('company_advertising', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.companyadvertising', verbose_name='Реклама компании')),
            ],
            options={
                'verbose_name': 'Реклама компании',
                'verbose_name_plural': 'Реклама компании',
                'ordering': ['-id'],
            },
        ),
    ]
