# Generated by Django 5.1.5 on 2025-02-02 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_companyadvertising_companyadvertisingitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVideoReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Видеоотзывы от наших клиентов', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Видеоотзывы от наших клиентов', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Видеоотзывы от наших клиентов', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Видеоотзывы от наших клиентов', max_length=255, null=True, verbose_name='Название')),
                ('sub_title', models.CharField(help_text='Например: Что говорят наши клиенты о нас', max_length=255, verbose_name='Подзаголовок')),
                ('sub_title_ru', models.CharField(help_text='Например: Что говорят наши клиенты о нас', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('sub_title_en', models.CharField(help_text='Например: Что говорят наши клиенты о нас', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('sub_title_uz', models.CharField(help_text='Например: Что говорят наши клиенты о нас', max_length=255, null=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Видеоотзывы от наших клиентов',
                'verbose_name_plural': 'Видеоотзывы от наших клиентов',
            },
        ),
        migrations.CreateModel(
            name='CompanyVideoReviewsItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='company_video_reviews_videos/', verbose_name='Видео')),
                ('company_video_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.companyvideoreviews', verbose_name='Видеоотзывы от наших клиентов')),
            ],
            options={
                'verbose_name': 'Видеоотзывы от наших клиентов',
                'verbose_name_plural': 'Видеоотзывы от наших клиентов',
                'ordering': ['-id'],
            },
        ),
    ]
