# Generated by Django 5.1.5 on 2025-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_companyvideoreviews_companyvideoreviewsitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Например: Как мы можем с вами связаться?', max_length=255, verbose_name='Вопрос')),
                ('question_ru', models.CharField(help_text='Например: Как мы можем с вами связаться?', max_length=255, null=True, verbose_name='Вопрос')),
                ('question_en', models.CharField(help_text='Например: Как мы можем с вами связаться?', max_length=255, null=True, verbose_name='Вопрос')),
                ('question_uz', models.CharField(help_text='Например: Как мы можем с вами связаться?', max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(help_text='Например: Мы можем с вами связаться по телефону или email', verbose_name='Ответ')),
                ('answer_ru', models.TextField(help_text='Например: Мы можем с вами связаться по телефону или email', null=True, verbose_name='Ответ')),
                ('answer_en', models.TextField(help_text='Например: Мы можем с вами связаться по телефону или email', null=True, verbose_name='Ответ')),
                ('answer_uz', models.TextField(help_text='Например: Мы можем с вами связаться по телефону или email', null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Часто задаваемый вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
    ]
