# Generated by Django 5.1.5 on 2025-02-02 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBrending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Брендинг - это не просто логотип и название', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Брендинг - это не просто логотип и название', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Брендинг - это не просто логотип и название', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Брендинг - это не просто логотип и название', max_length=255, null=True, verbose_name='Название')),
                ('sub_title', models.CharField(help_text='Например: Почему Брендинг важен для вашего бизнеса?', max_length=255, verbose_name='Подзаголовок')),
                ('sub_title_ru', models.CharField(help_text='Например: Почему Брендинг важен для вашего бизнеса?', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('sub_title_en', models.CharField(help_text='Например: Почему Брендинг важен для вашего бизнеса?', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('sub_title_uz', models.CharField(help_text='Например: Почему Брендинг важен для вашего бизнеса?', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('sub_title_2', models.CharField(help_text='Например: Это целостный образ вашей вашей компании, который формирует восприятие клиентов и выделяетвас на рынке', max_length=255, verbose_name='Подзаголовок 2')),
                ('sub_title_2_ru', models.CharField(help_text='Например: Это целостный образ вашей вашей компании, который формирует восприятие клиентов и выделяетвас на рынке', max_length=255, null=True, verbose_name='Подзаголовок 2')),
                ('sub_title_2_en', models.CharField(help_text='Например: Это целостный образ вашей вашей компании, который формирует восприятие клиентов и выделяетвас на рынке', max_length=255, null=True, verbose_name='Подзаголовок 2')),
                ('sub_title_2_uz', models.CharField(help_text='Например: Это целостный образ вашей вашей компании, который формирует восприятие клиентов и выделяетвас на рынке', max_length=255, null=True, verbose_name='Подзаголовок 2')),
            ],
            options={
                'verbose_name': 'Брендинг компании',
                'verbose_name_plural': 'Брендинг компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyBrendingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='company_brending_images/', verbose_name='Изображение')),
                ('company_brending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.companybrending', verbose_name='Брендинг компании')),
            ],
            options={
                'verbose_name': 'Брендинг компании',
                'verbose_name_plural': 'Брендинг компании',
                'ordering': ['-id'],
            },
        ),
    ]
