# Generated by Django 5.1.5 on 2025-02-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_companybrending_companybrendingitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Создаем бренд, который говорит сам за себя', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Создаем бренд, который говорит сам за себя', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Создаем бренд, который говорит сам за себя', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Создаем бренд, который говорит сам за себя', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Преимущество компании',
                'verbose_name_plural': 'Преимущества компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyFeaturesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='company_features_images/', verbose_name='Изображение')),
                ('title', models.CharField(help_text='Например: Нейминг', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Нейминг', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Нейминг', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Нейминг', max_length=255, null=True, verbose_name='Название')),
                ('sub_title', models.CharField(help_text='Например: Нейминг - это процесс создания уникального названия для вашего бизнеса', max_length=255, verbose_name='Подзаголовок')),
                ('sub_title_ru', models.CharField(help_text='Например: Нейминг - это процесс создания уникального названия для вашего бизнеса', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('sub_title_en', models.CharField(help_text='Например: Нейминг - это процесс создания уникального названия для вашего бизнеса', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('sub_title_uz', models.CharField(help_text='Например: Нейминг - это процесс создания уникального названия для вашего бизнеса', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('description', models.TextField(help_text='Например: Нейминг - это процесс создания уникального названия для вашего бизнеса', verbose_name='Описание')),
                ('description_ru', models.TextField(help_text='Например: Нейминг - это процесс создания уникального названия для вашего бизнеса', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(help_text='Например: Нейминг - это процесс создания уникального названия для вашего бизнеса', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(help_text='Например: Нейминг - это процесс создания уникального названия для вашего бизнеса', null=True, verbose_name='Описание')),
                ('company_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.companyfeatures', verbose_name='Преимущество компании')),
                ('tags', models.ManyToManyField(related_name='features_items', to='pages.tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Преимущество компании',
                'verbose_name_plural': 'Преимущества компании',
                'ordering': ['-id'],
            },
        ),
    ]
