# Generated by Django 5.1.5 on 2025-02-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_companyfeatures_companyfeaturesitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfeaturesitems',
            name='image_right',
            field=models.BooleanField(default=False, verbose_name='Изображение справа'),
        ),
    ]
