# Generated by Django 5.1.5 on 2025-02-04 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_companyfeaturesitems_image_right'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Креатив, который выделяет ваш бренд', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Креатив, который выделяет ваш бренд', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Креатив, который выделяет ваш бренд', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Креатив, который выделяет ваш бренд', max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Например: С более чем 10-летним опытом...', verbose_name='Описание')),
                ('description_ru', models.TextField(help_text='Например: С более чем 10-летним опытом...', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(help_text='Например: С более чем 10-летним опытом...', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(help_text='Например: С более чем 10-летним опытом...', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Видеопродукция',
                'verbose_name_plural': 'Видеопродукция',
            },
        ),
        migrations.CreateModel(
            name='VideoProductionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='video_production_logos/', verbose_name='Логотип')),
                ('title', models.CharField(help_text='Например: В BoldBrends мы уверены', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: В BoldBrends мы уверены', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: В BoldBrends мы уверены', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: В BoldBrends мы уверены', max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Например: С более чем 10-летним опытом...', verbose_name='Описание')),
                ('description_ru', models.TextField(help_text='Например: С более чем 10-летним опытом...', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(help_text='Например: С более чем 10-летним опытом...', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(help_text='Например: С более чем 10-летним опытом...', null=True, verbose_name='Описание')),
                ('video', models.FileField(upload_to='video_production_videos/', verbose_name='Видео')),
                ('video_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.videoproduction', verbose_name='Видеопродукция')),
            ],
            options={
                'verbose_name': 'Видеопродукция',
                'verbose_name_plural': 'Видеопродукция',
                'ordering': ['-id'],
            },
        ),
    ]
