# Generated by Django 5.1.5 on 2025-02-04 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_videoproduction_videoproductionitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Наши услуги по интеграции CRM', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Наши услуги по интеграции CRM', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Наши услуги по интеграции CRM', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Наши услуги по интеграции CRM', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Услуга CRM',
                'verbose_name_plural': 'Услуги CRM',
            },
        ),
        migrations.CreateModel(
            name='CRMServiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='crm_service_images/', verbose_name='Изображение')),
                ('image_right', models.BooleanField(default=False, verbose_name='Изображение справа')),
                ('title', models.CharField(help_text='Например: Интеграция CRM', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Интеграция CRM', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Интеграция CRM', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Интеграция CRM', max_length=255, null=True, verbose_name='Название')),
                ('crm_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.crmservice', verbose_name='Услуга CRM')),
                ('tags', models.ManyToManyField(related_name='crm_service_items', to='pages.tags', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Услуга CRM',
                'verbose_name_plural': 'Услуги CRM',
                'ordering': ['-id'],
            },
        ),
    ]
