# Generated by Django 5.1.5 on 2025-02-04 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_crmservice_crmserviceitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Маркетинговая поддержка', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Маркетинговая поддержка', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Маркетинговая поддержка', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Маркетинговая поддержка', max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Например: Мы предлагаем маркетинговую поддержку...', verbose_name='Описание')),
                ('description_ru', models.TextField(help_text='Например: Мы предлагаем маркетинговую поддержку...', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(help_text='Например: Мы предлагаем маркетинговую поддержку...', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(help_text='Например: Мы предлагаем маркетинговую поддержку...', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Маркетинговая поддержка',
                'verbose_name_plural': 'Маркетинговая поддержка',
            },
        ),
        migrations.CreateModel(
            name='MarketingSupportItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='video_production_logos/', verbose_name='Логотип')),
                ('title', models.CharField(help_text='Например: В BoldBrends мы уверены', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: В BoldBrends мы уверены', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: В BoldBrends мы уверены', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: В BoldBrends мы уверены', max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Например: С более чем 10-летним опытом...', verbose_name='Описание')),
                ('description_ru', models.TextField(help_text='Например: С более чем 10-летним опытом...', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(help_text='Например: С более чем 10-летним опытом...', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(help_text='Например: С более чем 10-летним опытом...', null=True, verbose_name='Описание')),
                ('video', models.FileField(upload_to='video_production_videos/', verbose_name='Видео')),
                ('marketing_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.marketingsupport', verbose_name='Маркетинговая поддержка')),
            ],
            options={
                'verbose_name': 'Маркетинговая поддержка',
                'verbose_name_plural': 'Маркетинговая поддержка',
                'ordering': ['-id'],
            },
        ),
    ]
