# Generated by Django 5.1.5 on 2025-02-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_marketingsupport_marketingsupportitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Что мы делаем', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Что мы делаем', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Что мы делаем', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Что мы делаем', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Услуги которые мы предлагаем',
                'verbose_name_plural': 'Услуги которые мы предлагаем',
            },
        ),
        migrations.CreateModel(
            name='ServiceOfferingItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='crm_service_images/', verbose_name='Изображение')),
                ('image_right', models.BooleanField(default=False, verbose_name='Изображение справа')),
                ('title', models.CharField(help_text='Например: Интеграция CRM', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Интеграция CRM', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Интеграция CRM', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Интеграция CRM', max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Например: Мы предлагаем интеграцию CRM...', verbose_name='Описание')),
                ('description_ru', models.TextField(help_text='Например: Мы предлагаем интеграцию CRM...', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(help_text='Например: Мы предлагаем интеграцию CRM...', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(help_text='Например: Мы предлагаем интеграцию CRM...', null=True, verbose_name='Описание')),
                ('service_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.serviceoffering', verbose_name='Услуги которые мы предлагаем')),
            ],
            options={
                'verbose_name': 'Услуги которые мы предлагаем',
                'verbose_name_plural': 'Услуги которые мы предлагаем',
                'ordering': ['-id'],
            },
        ),
    ]
