# Generated by Django 5.1.5 on 2025-02-04 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_serviceoffering_serviceofferingitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPostsItemsTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Например: Задача клиента', max_length=255, null=True, verbose_name='Название задачи')),
                ('title_ru', models.CharField(blank=True, help_text='Например: Задача клиента', max_length=255, null=True, verbose_name='Название задачи')),
                ('title_en', models.CharField(blank=True, help_text='Например: Задача клиента', max_length=255, null=True, verbose_name='Название задачи')),
                ('title_uz', models.CharField(blank=True, help_text='Например: Задача клиента', max_length=255, null=True, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, help_text='Например: Основной задачей клиента было увеличить выручку корейского ресторана на 70%', null=True, verbose_name='Описание задачи')),
                ('description_ru', models.TextField(blank=True, help_text='Например: Основной задачей клиента было увеличить выручку корейского ресторана на 70%', null=True, verbose_name='Описание задачи')),
                ('description_en', models.TextField(blank=True, help_text='Например: Основной задачей клиента было увеличить выручку корейского ресторана на 70%', null=True, verbose_name='Описание задачи')),
                ('description_uz', models.TextField(blank=True, help_text='Например: Основной задачей клиента было увеличить выручку корейского ресторана на 70%', null=True, verbose_name='Описание задачи')),
                ('company_post_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='pages.companypostsitems', verbose_name='Пост компании')),
            ],
            options={
                'verbose_name': 'Задача поста компании',
                'verbose_name_plural': 'Задачи постов компании',
                'ordering': ['-id'],
            },
        ),
    ]
