# Generated by Django 5.1.5 on 2025-02-04 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_companypostsitemstasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPostsItemsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Фотография 1', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Фотография 1', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Фотография 1', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Фотография 1', max_length=255, null=True, verbose_name='Название')),
                ('image', models.FileField(upload_to='company_posts_images/', verbose_name='Изображение')),
                ('description', models.TextField(help_text='Например: Фотография 1', verbose_name='Описание')),
                ('description_ru', models.TextField(help_text='Например: Фотография 1', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(help_text='Например: Фотография 1', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(help_text='Например: Фотография 1', null=True, verbose_name='Описание')),
                ('company_post_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.companypostsitems', verbose_name='Пост компании')),
            ],
            options={
                'verbose_name': 'Изображение поста компании',
                'verbose_name_plural': 'Изображения постов компании',
                'ordering': ['-id'],
            },
        ),
    ]
