# Generated by Django 5.1.5 on 2025-02-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_companypostsitemsresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypostsitemsresult',
            name='header',
            field=models.CharField(default=1, help_text='Например: Результаты', max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companypostsitemsresult',
            name='header_en',
            field=models.CharField(help_text='Например: Результаты', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='companypostsitemsresult',
            name='header_ru',
            field=models.CharField(help_text='Например: Результаты', max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='companypostsitemsresult',
            name='header_uz',
            field=models.CharField(help_text='Например: Результаты', max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
