# Generated by Django 5.1.5 on 2025-02-11 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_companypostsitemsresult_header_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Ресторан', max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(help_text='Например: Ресторан', max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(help_text='Например: Ресторан', max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(help_text='Например: Ресторан', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип бизнеса',
                'verbose_name_plural': 'Типы бизнеса',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: SMM продвижение', max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(help_text='Например: SMM продвижение', max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(help_text='Например: SMM продвижение', max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(help_text='Например: SMM продвижение', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип продвижения',
                'verbose_name_plural': 'Типы продвижения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='applicationform',
            name='business_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.businesstype', verbose_name='Тип бизнеса'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='promotion_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.promotiontype', verbose_name='Тип продвижения'),
        ),
    ]
