# Generated by Django 5.1.5 on 2025-02-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_businesstype_promotiontype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='applicationform',
            name='promotion_type',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='business_type',
            field=models.ManyToManyField(to='pages.businesstype', verbose_name='Типы бизнеса'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='promotion_type',
            field=models.ManyToManyField(to='pages.promotiontype', verbose_name='Типы продвижения'),
        ),
    ]
