# Generated by Django 5.1.5 on 2025-02-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_remove_applicationform_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='quantity_of_publications',
            field=models.TextField(blank=True, null=True, verbose_name='Количество публикаций в месяц'),
        ),
    ]
