# Generated by Django 5.1.5 on 2025-02-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_applicationform_quantity_of_publications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Новый сайт', max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(help_text='Новый сайт', max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(help_text='Новый сайт', max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(help_text='Новый сайт', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус Сайта',
                'verbose_name_plural': 'Статус Сайт',
                'ordering': ['name'],
            },
        ),
    ]
