# Generated by Django 5.1.5 on 2025-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_purposepromotiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='purpose_of_promotion',
            field=models.ManyToManyField(related_name='application_purpose', to='pages.purposepromotiontype', verbose_name='Цель продвижения'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='site_status',
            field=models.ManyToManyField(related_name='application_site_status', to='pages.sitestatustype', verbose_name='Статус сайта'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='business_type',
            field=models.ManyToManyField(related_name='application_business', to='pages.businesstype', verbose_name='Типы бизнеса'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='promotion_type',
            field=models.ManyToManyField(related_name='application_promotion', to='pages.promotiontype', verbose_name='Типы продвижения'),
        ),
    ]
