# Generated by Django 5.1.5 on 2025-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_applicationform_purpose_of_promotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='business_type',
            field=models.ManyToManyField(to='pages.businesstype', verbose_name='Типы бизнеса'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='promotion_type',
            field=models.ManyToManyField(to='pages.promotiontype', verbose_name='Типы продвижения'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='purpose_of_promotion',
            field=models.ManyToManyField(to='pages.purposepromotiontype', verbose_name='Цель продвижения'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='site_status',
            field=models.ManyToManyField(to='pages.sitestatustype', verbose_name='Статус сайта'),
        ),
    ]
