# Generated by Django 5.1.5 on 2025-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_alter_applicationform_business_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Нейминг', max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(help_text='Нейминг', max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(help_text='Нейминг', max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(help_text='Нейминг', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Услуги продвижения',
                'verbose_name_plural': 'Услуги продвижения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='applicationform',
            name='service_type',
            field=models.ManyToManyField(to='pages.servicetype', verbose_name='Услуги'),
        ),
    ]
