# Generated by Django 5.1.5 on 2025-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_videotype_applicationform_video_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Аналитика', max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(help_text='Аналитика', max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(help_text='Аналитика', max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(help_text='Аналитика', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='video_type',
            field=models.ManyToManyField(to='pages.videotype', verbose_name='Типы видео'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='task_type',
            field=models.ManyToManyField(to='pages.tasktype', verbose_name='Типы Задач'),
        ),
    ]
