# Generated by Django 5.1.5 on 2025-02-19 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_tasktype_alter_applicationform_video_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPostsItemsTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Например: реклама клиента', max_length=255, null=True, verbose_name='Название рекламы')),
                ('title_ru', models.CharField(blank=True, help_text='Например: реклама клиента', max_length=255, null=True, verbose_name='Название рекламы')),
                ('title_en', models.CharField(blank=True, help_text='Например: реклама клиента', max_length=255, null=True, verbose_name='Название рекламы')),
                ('title_uz', models.CharField(blank=True, help_text='Например: реклама клиента', max_length=255, null=True, verbose_name='Название рекламы')),
                ('description', models.TextField(blank=True, help_text='Например: Основной реклама клиента было увеличить выручку корейского ресторана на 70%', null=True, verbose_name='Описание рекламы')),
                ('description_ru', models.TextField(blank=True, help_text='Например: Основной реклама клиента было увеличить выручку корейского ресторана на 70%', null=True, verbose_name='Описание рекламы')),
                ('description_en', models.TextField(blank=True, help_text='Например: Основной реклама клиента было увеличить выручку корейского ресторана на 70%', null=True, verbose_name='Описание рекламы')),
                ('description_uz', models.TextField(blank=True, help_text='Например: Основной реклама клиента было увеличить выручку корейского ресторана на 70%', null=True, verbose_name='Описание рекламы')),
                ('company_post_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='pages.companypostsitems', verbose_name='Пост компании')),
            ],
            options={
                'verbose_name': 'Реклама поста компании',
                'verbose_name_plural': 'Реклама постов компании',
                'ordering': ['-id'],
            },
        ),
    ]
