# Generated by Django 5.1.5 on 2025-02-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_companypostsitemstarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPostsItemsImagesGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='company_posts_images/', verbose_name='Изображение')),
                ('post_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='pages.companypostsitemsimages', verbose_name='Изображение поста')),
            ],
            options={
                'verbose_name': 'Галерея изображений поста',
                'verbose_name_plural': 'Галерея изображений постов',
            },
        ),
    ]
