# Generated by Django 5.1.5 on 2025-02-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_companypostsitemsimagesgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companypostsitemsimagesgallery',
            options={'ordering': ['position'], 'verbose_name': 'Галерея изображений поста', 'verbose_name_plural': 'Галерея изображений постов'},
        ),
        migrations.AddField(
            model_name='companypostsitemsimagesgallery',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
