# Generated by Django 5.1.5 on 2025-02-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_alter_companypostsitemsimagesgallery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypostsitemsimages',
            name='image',
        ),
    ]
