# Generated by Django 5.1.5 on 2025-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_remove_companypostsitemsimages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Instagram', max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(help_text='Например: Instagram', max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(help_text='Например: Instagram', max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(help_text='Например: Instagram', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип соц. сетей',
                'verbose_name_plural': 'Типы соц. сетей',
            },
        ),
        migrations.AddField(
            model_name='applicationform',
            name='social_type',
            field=models.ManyToManyField(to='pages.socialtype', verbose_name='Типы соц. сетей'),
        ),
    ]
