# Generated by Django 5.1.5 on 2025-02-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_socialtype_applicationform_social_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='purpose_of_promotion',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='purpose_of_promotion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цель продвижения'),
        ),
    ]
