# Generated by Django 5.1.5 on 2025-02-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_remove_applicationform_purpose_of_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Лендинг', max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(help_text='Лендинг', max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(help_text='Лендинг', max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(help_text='Лендинг', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип сайта',
                'verbose_name_plural': 'Типы сайта',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='PurposePromotionType',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='site_type',
            field=models.ManyToManyField(to='pages.sitetype', verbose_name='Типы сайта'),
        ),
    ]
