# Generated by Django 5.1.5 on 2025-03-04 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_sitetype_delete_purposepromotiontype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Визитки', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Визитки', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Визитки', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Визитки', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Визитка',
                'verbose_name_plural': 'Визитки',
            },
        ),
        migrations.CreateModel(
            name='BusinessCardImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='business_card_images/', verbose_name='Изображение')),
                ('businesscards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesscards', to='pages.businesscards', verbose_name='Изображение визитки')),
            ],
            options={
                'verbose_name': 'Изображение визитки',
                'verbose_name_plural': 'Изображения визитки',
            },
        ),
    ]
