# Generated by Django 5.1.5 on 2025-03-09 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_businesscards_businesscardimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Что мы печатаем?', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Что мы печатаем?', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Что мы печатаем?', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Что мы печатаем?', max_length=255, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Услуга печати логотипа',
                'verbose_name_plural': 'Услуги печати логотипа',
            },
        ),
        migrations.CreateModel(
            name='PrintLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='printing_logo_images/', verbose_name='Лого')),
                ('printing_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing_service', to='pages.printingservice', verbose_name='Изображение визитки')),
            ],
            options={
                'verbose_name': 'Изображение лого',
                'verbose_name_plural': 'Изображения лого',
            },
        ),
    ]
