# Generated by Django 5.1.5 on 2025-03-09 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_printingservice_printlogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printlogo',
            options={'verbose_name': 'Логотип', 'verbose_name_plural': 'Логотипы'},
        ),
        migrations.AlterField(
            model_name='printlogo',
            name='logo',
            field=models.FileField(upload_to='print_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='printlogo',
            name='printing_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.printingservice'),
        ),
    ]
