# Generated by Django 5.1.5 on 2025-03-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_alter_printlogo_options_alter_printlogo_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvideoreviewsitems',
            name='video',
            field=models.URLField(help_text='Ссылка видео с ютуба', verbose_name='Видео'),
        ),
    ]
