# Generated by Django 5.1.5 on 2025-03-11 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_alter_companyvideoreviewsitems_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Дизайн и Разработка', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Дизайн и Разработка', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Дизайн и Разработка', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Дизайн и Разработка', max_length=255, null=True, verbose_name='Название')),
                ('sub_title', models.CharField(help_text='Например: Мы создадим не просто мечты', max_length=255, verbose_name='Подзаголовок')),
                ('sub_title_ru', models.CharField(help_text='Например: Мы создадим не просто мечты', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('sub_title_en', models.CharField(help_text='Например: Мы создадим не просто мечты', max_length=255, null=True, verbose_name='Подзаголовок')),
                ('sub_title_uz', models.CharField(help_text='Например: Мы создадим не просто мечты', max_length=255, null=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Дизайн и разработка',
                'verbose_name_plural': 'Дизайн и разработки',
            },
        ),
        migrations.CreateModel(
            name='DesignDevelopmentChapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Например: 01', max_length=255, verbose_name='Номер главы')),
                ('title', models.CharField(help_text='Например: Глава 1', max_length=255, verbose_name='Название главы')),
                ('title_ru', models.CharField(help_text='Например: Глава 1', max_length=255, null=True, verbose_name='Название главы')),
                ('title_en', models.CharField(help_text='Например: Глава 1', max_length=255, null=True, verbose_name='Название главы')),
                ('title_uz', models.CharField(help_text='Например: Глава 1', max_length=255, null=True, verbose_name='Название главы')),
                ('design_development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='pages.designdevelopment', verbose_name='Отдел маркетинга')),
            ],
            options={
                'verbose_name': 'Глава дизайн и разработка',
                'verbose_name_plural': 'Главы дизайн и разработки',
                'ordering': ['-id'],
            },
        ),
    ]
