# Generated by Django 5.1.5 on 2025-03-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_designdevelopment_designdevelopmentchapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproductionitems',
            name='video',
            field=models.URLField(help_text='Ссылка на видео', verbose_name='Видео'),
        ),
    ]
