# Generated by Django 5.1.5 on 2025-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_alter_videoproductionitems_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservicesitems',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для переноса'),
        ),
    ]
