# Generated by Django 5.1.5 on 2025-03-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_companyservicesitems_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvideoreviews',
            name='video_type',
            field=models.CharField(blank=True, choices=[('other', 'Отзывы для остальных стр'), ('production', 'Отзывы для видеопродакшен страницы'), ('blog', 'Видео для блога')], max_length=20, null=True, verbose_name='Тип видео'),
        ),
    ]
