# Generated by Django 5.1.5 on 2025-03-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0054_companyvideoreviews_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvideoreviews',
            name='video_type',
            field=models.CharField(blank=True, choices=[('other', 'Отзывы для остальных стр'), ('production', 'Отзывы для видеопродакшен страницы'), ('blog', 'Видео для блога')], max_length=20, null=True, unique=True, verbose_name='Тип видео'),
        ),
        migrations.AddConstraint(
            model_name='companyvideoreviews',
            constraint=models.UniqueConstraint(fields=('video_type',), name='unique_video_type'),
        ),
    ]
