# Generated by Django 5.1.5 on 2025-03-14 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_alter_companyvideoreviews_video_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Статьи', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Например: Статьи', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Например: Статьи', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Например: Статьи', max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Например: Статьи что помогут вам следить за новостями и нашими работами', verbose_name='Описание')),
                ('description_ru', models.TextField(help_text='Например: Статьи что помогут вам следить за новостями и нашими работами', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(help_text='Например: Статьи что помогут вам следить за новостями и нашими работами', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(help_text='Например: Статьи что помогут вам следить за новостями и нашими работами', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='ArticlePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Загрузите изображение', upload_to='article_posts/', verbose_name='Изображение')),
                ('title', models.CharField(help_text='Статья 1', max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(help_text='Статья 1', max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(help_text='Статья 1', max_length=255, null=True, verbose_name='Название')),
                ('title_uz', models.CharField(help_text='Статья 1', max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание для статьи 1', verbose_name='Описание')),
                ('description_ru', models.TextField(help_text='Описание для статьи 1', null=True, verbose_name='Описание')),
                ('description_en', models.TextField(help_text='Описание для статьи 1', null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(help_text='Описание для статьи 1', null=True, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.article', verbose_name='Статьи')),
            ],
            options={
                'verbose_name': 'Пост статьи',
                'verbose_name_plural': 'Посты статьи',
            },
        ),
    ]
