# Generated by Django 5.1.5 on 2025-03-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0056_article_articleposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleposts',
            name='link',
            field=models.URLField(default=1, verbose_name='Ссылка от яндекс дзен'),
            preserve_default=False,
        ),
    ]
