# Generated by Django 5.1.5 on 2025-03-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_articleposts_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='social_media_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='subscribers',
            field=models.CharField(blank=True, help_text='Например: +10,5 подписчиков', max_length=255, null=True, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='subscribers_en',
            field=models.CharField(blank=True, help_text='Например: +10,5 подписчиков', max_length=255, null=True, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='subscribers_ru',
            field=models.CharField(blank=True, help_text='Например: +10,5 подписчиков', max_length=255, null=True, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='subscribers_uz',
            field=models.CharField(blank=True, help_text='Например: +10,5 подписчиков', max_length=255, null=True, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title',
            field=models.CharField(blank=True, help_text='Например: Instagram', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title_en',
            field=models.CharField(blank=True, help_text='Например: Instagram', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Например: Instagram', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='title_uz',
            field=models.CharField(blank=True, help_text='Например: Instagram', max_length=255, null=True, verbose_name='Название'),
        ),
    ]
