# Generated by Django 5.1.5 on 2025-01-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: "Тратите много времени на поиск брендов?"', max_length=255, verbose_name='Название')),
                ('sub_title', models.CharField(help_text='Например: "Мы поможем вам найти бренды, которые вам нужны"', max_length=255, verbose_name='Подзаголовок')),
                ('button_text', models.CharField(help_text='Например: "Узнать больше"', max_length=255, verbose_name='Текст кнопки')),
                ('image', models.FileField(upload_to='banners/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['-id'],
            },
        ),
    ]
