# Generated by Django 5.1.5 on 2025-03-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_banners_button_text_en_banners_button_text_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Новый кейс на сайте!', null=True, verbose_name='Текст')),
                ('text_ru', models.TextField(blank=True, help_text='Новый кейс на сайте!', null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, help_text='Новый кейс на сайте!', null=True, verbose_name='Текст')),
                ('text_uz', models.TextField(blank=True, help_text='Новый кейс на сайте!', null=True, verbose_name='Текст')),
                ('link', models.URLField(blank=True, help_text='Например: https://example.com/case/', null=True, verbose_name='Ссылка')),
                ('link_ru', models.URLField(blank=True, help_text='Например: https://example.com/case/', null=True, verbose_name='Ссылка')),
                ('link_en', models.URLField(blank=True, help_text='Например: https://example.com/case/', null=True, verbose_name='Ссылка')),
                ('link_uz', models.URLField(blank=True, help_text='Например: https://example.com/case/', null=True, verbose_name='Ссылка')),
                ('banner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banners.banners', verbose_name='Баннер')),
            ],
            options={
                'verbose_name': 'Текст баннера',
                'verbose_name_plural': 'Тексты баннеров',
            },
        ),
    ]
