# Generated by Django 5.1.5 on 2025-03-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_bannertext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannertext',
            name='link_en',
        ),
        migrations.RemoveField(
            model_name='bannertext',
            name='link_ru',
        ),
        migrations.RemoveField(
            model_name='bannertext',
            name='link_uz',
        ),
    ]
